name: dart_class_wrapper
description: Wrapper for a simplified partial mocking in Unit Tests
version: 1.0.1
homepage: https://github.com/lyskouski/dart_class_wrapper
repository: https://github.com/lyskouski/dart_class_wrapper
issue_tracker: https://github.com/lyskouski/dart_class_wrapper/issues

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  analyzer: ^5.11.0
  build: ^2.4.1
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  lints: ^2.0.0
  test: ^1.16.0
