name: publishing

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d

      - name: Install Dependencies
        run: |
          dart pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Publish - dry run
        run: dart pub publish --dry-run
        working-directory: ${{ inputs.working-directory }}

# [TBD] Not working by now
#      - name: Publish to pub.dev
#        run: dart pub publish -f
#        working-directory: ${{ inputs.working-directory }}